config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, path: 'accounts', controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :hashtag, only: :show

  get 'all-users', to: 'users#index'

  authenticated :user do
    root 'newsfeeds#show'
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  concern :likable do
    post 'like', to: 'likes#create'
    delete 'dislike', to: 'likes#destroy'
  end
  
  resources :posts, only: %i[create edit update destroy], shallow: true, concerns: :likable do
    resources :comments, only: %i[edit update destroy create], concerns: :likable
  end

  get 'received_requests', to: 'incoming_requests#index'
  get 'sent_requests', to: 'outgoing_requests#index'
  
  resources :users, only: :none, path: :relationships do
    member do
      delete 'reject_request', to: 'incoming_requests#destroy'
    end
    
    member do
      post 'send_request', to: 'outgoing_requests#create'
      delete 'remove_request', to: 'outgoing_requests#destroy'
    end

    member do
      post 'accept_request', to: 'friendships#create'
      delete 'remove_friend', to: 'friendships#destroy'
    end
  end

  resources :users, only: :none, path: '', param: :username do
    member do
      get 'friends', to: 'friendships#index'
    end
    resource :profile, path: '', only: %i[show edit update]
    resources :posts, path: '', only: :show
  end

end

# /:id/likes/:likable_type
# /:id/dislikes/:likable_type
# /:user_username/requests/:receiver_id

app/controllers/outgoing_requests_controller.rb
class OutgoingRequestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @outgoing_requests = current_user.outgoing_requests
  end

  def create
    @receiver = User.find(params[:id])
    current_user.sends_request(@receiver)
    flash[:notice] = 'Request Sent!'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @request = current_user.outgoing_requests.find_by(receiver_id: params[:id])
    current_user.unsend_request(@request)
    flash[:notice] = 'Request Cancelled!'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/outgoing_requests_helper.rb
module OutgoingRequestsHelper
end

app/views/outgoing_requests/_outgoing_request.html.erb
<% @outgoing_requests.each do |outgoing_request| %>
  <div class="card mb-4 mx-auto p-2 shadow" style="max-width: 768px;"><!-- Each request box starts -->  
    <div class="row no-gutters request-box">   

      <div class="user-avatar col-4 my-auto"><!-- Left half starts -->
        <%= image_tag avatar(outgoing_request.receiver, :profile), class: 'rounded-circle card-img img-thumbnail' %>
      </div><!-- Left half ends -->

      <div class="col-8"><!-- Right half starts -->
        <div class="card-body">        
          <h5 class="card-title"><%= link_to outgoing_request.receiver.username,  user_profile_path(outgoing_request.receiver) %></h5>
          <p class="card-text"><%= outgoing_request.receiver.profile.about_me %></p>

          <div class="row mt-5 pt-5 px-0 my-auto">

            <p class="col-md card-text my-md-auto"><em><small class="text-muted">Sent <%= time_ago_in_words(outgoing_request.created_at) %> ago</small></em></p>
            <div class="col-md cancel-request-button card-text">
              <%= link_to 'Cancel Request', remove_request_user_path(outgoing_request.receiver.id), method: :delete, class: "btn btn-primary btn-sm float-md-right" %>
            </div>

          </div>

        </div>
      </div><!-- Right half ends -->

    </div>
  </div><!-- Each request box ends -->
<% end %>

app/views/outgoing_requests/index.html.erb
<div class="outgoing-requests">
    <%= render 'outgoing_request' %>
</div>