config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, path: 'accounts', controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :hashtag, only: :show

  get 'all-users', to: 'users#index'

  authenticated :user do
    root 'newsfeeds#show'
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  concern :likable do
    post 'like', to: 'likes#create'
    delete 'dislike', to: 'likes#destroy'
  end
  
  resources :posts, only: %i[create edit update destroy], shallow: true, concerns: :likable do
    resources :comments, only: %i[edit update destroy create], concerns: :likable
  end

  get 'received_requests', to: 'incoming_requests#index'
  get 'sent_requests', to: 'outgoing_requests#index'
  
  resources :users, only: :none, path: :relationships do
    member do
      delete 'reject_request', to: 'incoming_requests#destroy'
    end
    
    member do
      post 'send_request', to: 'outgoing_requests#create'
      delete 'remove_request', to: 'outgoing_requests#destroy'
    end

    member do
      post 'accept_request', to: 'friendships#create'
      delete 'remove_friend', to: 'friendships#destroy'
    end
  end

  resources :users, only: :none, path: '', param: :username do
    member do
      get 'friends', to: 'friendships#index'
    end
    resource :profile, path: '', only: %i[show edit update]
    resources :posts, path: '', only: :show
  end

end

# /:id/likes/:likable_type
# /:id/dislikes/:likable_type
# /:user_username/requests/:receiver_id

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authorize_user(user)
    return if user == current_user
    flash[:alert] = 'You are not authorized!'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def avatar(user, size)
    image_sizes = { x_small: 30, small: 45, medium: 80, large: 100, x_large: 130, profile: 300 }
    email_digest = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "//www.gravatar.com/avatar/#{email_digest}?&s=#{image_sizes[size]}"
    gravatar_url
  end

  def choose_avatar(user, size)
    if user.image_path
      return user.image_path
    else
      avatar(user, size)
    end
  end

  def show_navbar
    render 'navbar' unless controller_name == "sessions" || controller_name == "registrations"
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/views/application/_navbar.html.erb
<div class="navbar navbar-dark bg-dark navbar-expand-lg mb-4 sticky-top">
  <div class="container">
    <div class="navbar-brand header-font">
      <%= link_to 'Devium', root_path, class: 'h2' %>
    </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <% if signed_in? %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">

           <li class="nav-item">
              <%= link_to "Find friends", all_users_path, class: 'nav-link' %>
          </li> 

          <li class="nav-item">
              <%= link_to "Pending Requests <span class='badge badge-secondary'>#{current_user.received_requests_count}</span>".html_safe, received_requests_path, class: 'nav-link' %>
          </li> 

          <li class="nav-item">
            <%= link_to "Sent Requests <span class='badge badge-secondary'>#{current_user.sent_requests_count}</span>".html_safe, sent_requests_path, class: 'nav-link' %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link p-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar(current_user, :small), class: 'rounded-circle' %>
            </a>

            <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="navbarDropdown">
              <%= link_to 'Profile', user_profile_path(current_user), class: 'dropdown-item nav-link' %>
              <%= link_to 'Friends', friends_user_path(current_user.username), class: 'dropdown-item nav-link' %>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item nav-link' %>
            </div>

          </li>

        </ul>
      </div>
    <% else %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">

          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          
        </ul>
      </div>
    <% end %>
  </div>
</div>